// Import ES-module factories generated by emscripten:
import createC from "../pkg/c_demo.js";
import createCpp from "../pkg/cpp_demo.js";

const C = await createC();     // loads c_demo.wasm
const CPP = await createCpp(); // loads cpp_demo.wasm

// Plain C exports via cwrap (use 'string'/'number' for types)
const greet = C.cwrap("greet", "string", ["string"]);
const count_primes = C.cwrap("count_primes", "number", ["number"]);

// C++ Embind exports are methods on the module:
const greet_cpp = CPP.greet_cpp;
const count_primes_cpp = CPP.count_primes_cpp;

document.getElementById("hello").onclick = () => {
  const name = document.getElementById("name").value || "world";
  document.getElementById("greeting").textContent = greet(name);
};
document.getElementById("hello_cpp").onclick = () => {
  const name = document.getElementById("name").value || "world";
  document.getElementById("greeting").textContent = greet_cpp(name);
};

document.getElementById("count").onclick = () => {
  const n = +document.getElementById("limit").value || 0;
  const t0 = performance.now();
  const c = count_primes(n);
  const t1 = performance.now();
  document.getElementById("result").textContent =
    `${c} primes (C) in ${(t1 - t0).toFixed(1)} ms`;
};
document.getElementById("count_cpp").onclick = () => {
  const n = +document.getElementById("limit").value || 0;
  const t0 = performance.now();
  const c = count_primes_cpp(n);
  const t1 = performance.now();
  document.getElementById("result").textContent =
    `${c} primes (C++) in ${(t1 - t0).toFixed(1)} ms`;
};
